# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9efc746bdc0d4230619911ea2af0b7a06894ef0712c09fa44c8c0d031a16d825433c98a50102a22093b4803afb76060a74cd4d72a275a13480e81707cc8a4c

test:
  secret_key_base: c18fc79f7425b9a0619c4f296cffb0b57ddf713eeca43f91a8ca8aaeb6441e5ef391bde445381665c1ba4c78dc0c1c15b63703888aa8c4fa80d2ec68320f2dad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
